### ISSUE TITLE
Ranks=True - NameError: name 'current_lineage_id' is not defined

### ISSUE THREAD

**Issue by Niwradel** [HadrienG/taxadb#70]
Hello, first of all, tank you for developing this python script (very useful for my work).
I tried your exemple : 

`taxid.lineage_name(33208, reverse=True)`
and it works as: 
`
['cellular organisms', 'Eukaryota', 'Opisthokonta', 'Metazoa']`

But when I want to get also the rank informations: 

`taxid.lineage_name(33208, reverse=True,ranks=True)
`
I get the followgin error message: 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/beegfs/home/user/.local/lib/python3.7/site-packages/taxadb/taxid.py", line 107, in lineage_name
    lineages.append((rank, current_lineage_id))
NameError: name 'current_lineage_id' is not defined
```

Have you an idea what is going on ? 

In the file `taxadb/taxid.py`
for the function  **lineage_name**
should it not be : `lineages.append((rank, current_lineage))` rather then  `lineages.append((rank, current_lineage_id))` ?

**Comment by HadrienG** [comment]
Hi,

Thanks for reporting this!
I'll take a look and come back to you.

/Hadrien

**Comment by DrAntoine** [comment]
Hi all, 

I had the same problem while working on wiz, another project which uses taxadb. After renaming "current_lineage_id" to "current_lineage" on line 107 the bug seems to be fixed. I am not an expert in pull requests therefore I do not know how to propose the corrected file, but the correction in question is quite minimal if I have flushed out the bug.

best regards, 
/DrAntoine
